services:
  localrestserver:
    build:
      context: .
    volumes:
      - ./mnt:/mnt
    restart: always
    user: "1000:1000"
    networks:
      - localrestserver

networks:
  localrestserver:
    name: localrestserver