services:
  localrestserver:
    build:
      context: .
    volumes:
      - ./mnt:/mnt
    restart: always
    user: "1000:1000"
    networks:
      - localrestserver
    environment:
      - APPSETTINGS_IPADDRESS=localrestserver

networks:
  localrestserver:
    name: localrestserver