services:
  localrestserver:
    build:
      context: .
    volumes:
      - db:/mnt
    restart: always
    user: "33:33"
    networks:
      - main
    environment:
      - APPSETTINGS_IPADDRESS=localrestserver

networks:
  main:
    name: main
    external: true

volumes:
  db:
