services:
  localrestserver:
    build:
      context: .
    volumes:
      - db:/mnt
    restart: always
    user: "33:33"
    networks:
      - localrestserver
    environment:
      - APPSETTINGS_IPADDRESS=localrestserver

networks:
  localrestserver:
    name: localrestserver

volumes:
  db:
